version: '3.3'

services:
  web:
    build: ./services/odmf
    env_file:
      - .env
    volumes:
      - ./instance/:/srv/odmf/
    ports:
      - ${ODMF_PORT}:${ODMF_PORT}
    depends_on:
      - db
    restart: unless-stopped
    working_dir: /srv/odmf
    command: python3 /srv/start-odmf.py
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER:-db_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-db_passw}
      - POSTGRES_DB=${DB_NAME:-odmf}
    restart: unless-stopped
  db_backup:
    build: ./services/backup
    environment:
      - DB_URL=postgresql://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME
      - BACKUP_ZIP=gzip
    volumes:
      - ./backup/:/var/backup/
    depends_on:
      - db
    tty: true
volumes:
  postgres_data:

